name = "remix-cloudflare-workers-template"

main = "./src/server.ts"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"
assets = { directory = "../remix-app/build/client", binding = "ASSETS", not_found_handling = "none" }

[durable_objects]
bindings = [
  {name = "EXAMPLE_DO", class_name = "ExampleDO", script_name = "remix-cloudflare-workers-template"}
]

[[migrations]]
new_classes = ["ExampleDO"]
tag = "v1"

[env.local]

[env.local.durable_objects]
bindings = [
  {name = "EXAMPLE_DO", class_name = "ExampleDO", script_name = "remix-cloudflare-workers-template-local"}
]
